### ISSUE TITLE
Create package.json

### ISSUE THREAD

**Issue by KristjanESPERANTO** [RaspiManu/MMM-FrameLight#3]
I am working on a new module list, which you can see [here](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/). If you search for your module in it, you will see that it looks a bit bland at the moment, as a screenshot and tags are missing.

You can change that by adding a `package.json` file. The information that is currently used from that file is the license information (the screenshot can only be displayed if the license is free) and the keywords (these are then displayed as tags).

[Here is an example of a package.json](https://github.com/KristjanESPERANTO/MMM-RandomQuotes/blob/master/package.json).

It would be nice if you would add one to your repository :slightly_smiling_face:

**Comment by RaspiManu** [comment]
Dear @KristjanESPERANTO 

thank you very much for reaching out to us. I already had some thoughts about how to present our module in your list, since I asked you about our media placement in a separate branch in the MM forum. I will take a look at your new hints on this and see what I can do.

Best wishes
RaspiManu

**Comment by KristjanESPERANTO** [comment]
Ah, now I remember. One of the problems was that your images are in a different branch, which my script wouldn't cover.

I am currently working mainly on automating the process and don't know when I will be able to tackle this.

So the packge.json would initially at least bring the keywords :slightly_smiling_face:

**Comment by RaspiManu** [comment]
Dear @KristjanESPERANTO

I just created a pull request that adds a package.json and a presentation picture to our master branch, so our module should be better represented in your list. After @ViatorisBaculum reviews it, this issue will be closed automatically.

Best wishes
RaspiManu

**Comment by KristjanESPERANTO** [comment]
Nice. I'm looking forward to it :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
Now it looks great. Thank you! :smiley:
